### ISSUE TITLE
Add note about argument order

### ISSUE THREAD

**Issue by zspitz** [pandoc/pandoc-action-example#3]
When running pandoc directly from the command line, the input file can be passed before, after, or between other options. For example, the following (from the [User's Guide](https://pandoc.org/MANUAL.html#creating-a-pdf)):

>     pandoc test.txt -o test.pdf

puts the input file first, followed by options.

However, [my experience has been](https://github.com/jgm/pandoc-website/issues/38) that when using the pandoc container in an action, and the `pandoc` executable is not passed as one of the arguments, the input file must be the last argument passed. Otherwise, something like this:

    with:
      args: "docs/patient-guide.md -o output.pdf -t html"

[fails with an error](https://github.com/zspitz/tidepool-hebrew-docs/runs/426523790?check_suite_focus=true):

> Syntax error: unexpected newline

It might be a good idea to document this.

**Comment by maxheld83** [comment]
I personally think that the problem here are the complications introduced by the smart entrypoint script, as per https://github.com/jgm/pandoc-website/issues/38.
I'd rather not propagate the complexity into this example.

Instead, I've suggested in https://github.com/pandoc/dockerfiles/issues/78 to revert to a simple `ENTRYPOINT`, which would meet your expectations here broken.
