### ISSUE TITLE
Install additional packages to the docker file

### ISSUE THREAD

**Issue by SebastianZug** [pandoc/pandoc-action-example#6]
Hi maxheld83,
stupid question related to the included docker container. Is it possible to use the "standard" docker as shown in the examples but extend it by individually required packages? Or do I need to define a new container in this case?

More specifically, I used box drawing unicodes in my document. For this purpose `pmboxdraw.sty' needs to be installed. By the way, this package should be part of the texlive standard installation and I did not understand why it is not included. 

Many thanks for your help!

Sebastian

**Comment by maxheld83** [comment]
You can always override the [entrypoint](https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime) with another executible such as `bash` and then pass commands in bash such as whatever is necessary to install the desired latex package.
You can then pass the `pandoc` command.
To make it easier, you can also write the two commands in a script, and call that.
For more information of how to override the entrypoint and `docker run` in general (which is what's the workhorse behind this) see https://docs.docker.com/engine/reference/run/.

You could also inquire with the upstream pandoc docker image project, why the missing package isn't installed: https://github.com/pandoc/dockerfiles.
After many painful years I know try to avoid LaTeX like the plague, so I'm not much help here and anyway that's an upstream concern.

Lastly, you can always build your own docker image based on https://github.com/pandoc/dockerfiles., and use that to run the action, but that carries some overweight.

Hope this helps.
Closing this for now because it seems a bit out of scope of these examples.

**Comment by SebastianZug** [comment]
Many thanks! This extends the options of a pandoc document generation process again! I will test it and provide an extended example.

**Comment by alerque** [comment]
@maxheld83, You don't have to override the entrypoint. The entrypoint script is already a smart script that runs Pandoc if you pass it arguments, but if you run something that is a shell command it will run that directly. That means if you want to run `bash` in the container instead of automatically running `pandoc` just pass *bash* as the first argument to your docker run command.

This allows you to mess around and even install things, but it doesn't really solve the OP's issue because anything you do in there will be ephemeral to that run.

**Comment by maxheld83** [comment]
thanks @alerque -- I know that (was?) the behavior. My understanding from the discussion in https://github.com/pandoc/dockerfiles/issues/78 was that the smarts of the script are or would be reverted in future.
